name: Lint, Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.2.2

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load cached Poetry installation
        uses: actions/cache@v3
        with:
          path: ~/.local # the path depends on the OS
          key: poetry-1 # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load Cached Venv
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: "venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}"

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Verify python imports order
        run: poetry run isort --check src tests

      - name: Verify code formatting (Black)
        run: poetry run black --verbose --check src tests

      - name: Enforce code style (Flake8)
        run: poetry run flake8 src tests

      - name: Run Tests
        env:
          AWS_ACCESS_KEY_ID: doesnt-matter
          AWS_SECRET_ACCESS_KEY: doesnt-matter
        run: make test
